export const DsProject = [
  {
    id: 1,
    title: "Predict credit default",
    alt: "predict credit default project for data science students",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Moodys-Project.webp",
    desc: "  Develop a prediction model for identifying probable credit default    for a retail bank. The bank has a huge dataset of credit card    customers.",
    width: "107",
    height: "50",
  },
  {
    id: 2,
    title: "Google Mobility data ",
    alt: "Work on realtime project with our data science projects",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Google_logo.webp",
    desc: "   Identification of COVID-19 surge in cases based on mobility within    the country.The goal is to study the pattern of COVID-19 cases in    different regions in India.",
    width: "95",
    height: "50",
  },
  {
    id: 3,
    title: "Uber - fare prediction",
    alt: "Work on realtime project with our use data science tools like powerBI",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Uber.webp",
    desc: "   Predicting fare price based on demand and supply.You will have to    analyse the data of the ride sharing applications to identify the    factors that are driving the demand.",
    width: "70",
    height: "36",
  },
  {
    id: 4,
    title: "Predict heart failure",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/proscia.webp",
    desc: "  Cardiovascular diseases (CVDs) are the number 1 cause of death    globally. So here have to create a model that could predict heart    failure before its occurrence.",
    width: "107",
    height: "50",
  },
  {
    id: 5,
    title: "YouTube video analytics",
    alt: "use Data science techniques to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Youtube.webp",
    desc: "  Collect record of data on videos trending on YouTube. Analyze the    data to predict the sentiment of the videos, study the comments by    categorizing the videos.",
    width: "107",
    height: "50",
  },
  {
    id: 6,
    title: "Analyze exchange rates",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Bloombreg.webp",
    alt: "use Data science techniques to solve analytics problems",
    desc: "    Determine the forecast. Model a program to forecast value of a currency in global market. Study and analyse the data to predict exchange rates in global markets.",
    width: "107",
    height: "50",
  },
  {
    id: 7,
    title: "Understand mobile banking",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "    Analyze customers usage of mobile banking like at Razorpay. Use the    dummy data to create a model like razorpay.",
    width: "107",
    height: "50",
  },
  {
    id: 8,
    title: "Mercedes-Benz – Reduce time",
    alt: "mercedez logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mercedez.webp",
    desc: "  Reduce the time for a Mercedes-Benz to reach the market by    optimizing the testing time. Elimination of bench time would reduce    the total testing duration.",
    width: "72",
    height: "40",
  },
  {
    id: 9,
    title: "Amazon Food Reviews",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "  Classify food reviews based on customer feedback. You will perform    sentiment analysis on each product on the list. use NLP to identify    the sentiment of customers.",
    width: "93",
    height: "28",
  },
  {
    id: 10,
    title: "Predict Machine Maintenance",
    alt: "lyft logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/lyft.webp",
    desc: " Classify food reviews based on customer feedback. You will perform sentiment analysis on each product on the list. use NLP to identify the sentiment of customers.",
    width: "110",
    height: "50",
  },
  {
    id: 11,
    title: "Google Playstore analytics",
    alt: "googleplay logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Google-play.webp",
    desc: "  Predict the factors that contribute to the success of an     application. store. Your task will be to draw actionable insights    for developers to work on.",
    width: "110",
    height: "60",
  },
  {
    id: 12,
    title: "Recommend Music- Spotify",
    alt: "soptify logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/soptify-logo.webp",
    desc: "  work on the dataset and Find a Geographical connection with popular    songs. Analyze and identify the geographical connection with the    popular songs.",
    width: "110",
    height: "60",
  },
];
export const FsProject = [
  {
    id: 1,
    title: "Authentication",
    alt: "cisco logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/cisco.webp",
    desc: "  Create authentication technology to give access, Correspond to those    stored in a database of authorized users.",
    width: "220",
    height: "37",
  },
  {
    id: 2,
    title: "CRUD",
    alt: "sql logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/sql.webp",
    desc: " Create an online tool that allows users to edit, delete, and add    records while viewing the database's contents in list format.",
    width: "170",
    height: "35",
  },
  {
    id: 3,
    title: "Video Conferencing App",
    alt: "do full stack projects with our full stack developer course likee google meet logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/gmeet.webp",
    desc: "This is an innovative full-stack web development project with    seamless audio-video call management capabilities.",
    width: "280",
    height: "35",
  },
  {
    id: 4,
    title: "API Integration",
    alt: "do the api intregration with full stack course like accuweather",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/accuweather.webp",
    desc: "  Cardiovascular diseases (CVDs) are the number 1 cause of death    globally. So here have to create a model that could predict heart    failure before its occurrence.",
    width: "230",
    height: "37",
  },
  {
    id: 5,
    title: "Payment Gateway",
    alt: "build a payment gateway google pay",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/gpay.webp",
    desc: "  Learn how to integrate the payment gateway that online businesses    use to authorise and process credit card and debit payments.",
    width: "212",
    height: "33",
  },
  {
    id: 6,
    title: "Travel Booking Application",
    alt: "build a travel booking project with our full stack course like happay logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/happay.webp",
    desc: "   The associated website must provide registration, login and logout,    and profile building and modification.",
    width: "234",
    height: "42",
  },
  {
    id: 7,
    title: "Workout Application",
    alt: "trx logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/trx.webp",
    desc: "  Modern fitness monitors go much beyond the standard pedometer. Users' heart rates and run times are tracked and stored.",
    width: "135",
    height: "25",
  },
  {
    id: 8,
    title: "Blog Site",
    alt: "wix logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/wix.webp",
    desc: "   Create a CMS website or application which has a better content    optimization and visuals optimization.",
    width: "50",
    height: "19",
  },
  {
    id: 9,
    title: "Home Service Application",
    alt: "codiant logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/codiant.webp",
    desc: "  Local services will be listed on this website. Local businesses and    services can promote their offerings, pricing, and locations.",
    width: "250",
    height: "26",
  },
  {
    id: 10,
    title: "VR Based Application",
    alt: "cryenine logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/cryengine.webp",
    desc: "Make a VR programme with enhanced audiovisual capabilities. Learn    how to use VR applications to relieve anxiety and tension.",
    width: "277",
    height: "26",
  },
  {
    id: 11,
    title: "To-Do List Application",
    alt: "Task logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/task.webp",
    desc: "  You will get knowledge about creating and improving multi-use panels    and components through this project.",
    width: "200",
    height: "24",
  },
  {
    id: 12,
    title: "Food Delivery Application",
    alt: "swiggy logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/swiggy.webp",
    desc: "  Create a sizable, feature-rich meal delivery website through this    project. Build a backend framework for restaurant registration.",
    width: "200",
    height: "24",
  },
  {
    id: 13,
    title: "Chatting/Messaging App",
    alt: "telegram logo",
    img: "  https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/telegram.png",
    desc: " Create a decent- looking and incredibly functional front- end. This    project focuses on creating a user- friendly chat applications.",
    width: "85",
    height: "23",
  },
  {
    id: 14,
    title: "Stock Investment App",
    alt: "centra logo",
    img: "  https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/centra.webp",
    desc: " You will get knowledge about creating and improving multi-use panels     and components through this project.",
    width: "169",
    height: "24",
  },
  {
    id: 15,
    title: "Online Code Editor",
    alt: "leetcode logo",
    img: " https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/leetcode.webp",
    desc: "  Your attention will be drawn to prototyping, quick hosting of newly    published apps, and seamless collaboration.",
    width: "200",
    height: "24",
  },
];
export const webProject = [
  {
    id: 1,
    title: "E-Commerce",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon-flipkart-ecommerce-project.webp",
    alt: "learn git and many tools and build E-commerce project like flipkart,amazon",
    desc: " Create a dynamic and responsive environment.E-commerce web application using technologies such as Angular, Hibernate,MySQL, and Docker.",
    width: "200",
    height: "34",
  },
  {
    id: 2,
    title: "Chatbot Application",
    alt: "work web development projects and develop chat bot application",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/slush-icon.webp",
    desc: "Chatbots are computer programmes that mimic spoken or written language. So these mimic communication or contact with a real person.",
    width: "200",
    height: "34",
  },
  {
    id: 3,
    title: "Show Booking App",
    alt: "become a full stack web developer work on project like bookmyshow",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/bookmyshow.webp",
    desc: "   Create an entertainment application like BookMyShow using your back-end knowledge, API development, and HTML and CSS skills.",
    width: "200",
    height: "34",
  },
  {
    id: 4,
    title: "Courier Tracking System",
    alt: "prohance logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/prohance.webp",
    desc: " Contains information about both administrator and user functions, including office registration, creating users, viewing suggestions and complaints of users.",
    width: "266",
    height: "42",
  },
  {
    id: 5,
    title: "Fuel Delivery Flutter App",
    alt: "fuelbody logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/fuelbody.webp",
    desc: "   When it comes to refilling their vehicles, businesses who manage a fleet of vehicles, such as taxi and cab firms,intercity and long-distance bus service providers, trucking agencies, etc., frequently run into problems.",
    width: "83",
    height: "25",
  },
  {
    id: 6,
    title: "Healthcare App",
    alt: "genris logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/generis.webp",
    desc: "  Build a dynamic and effective healthcare app. Create a rich UI for effective diagnosis and health advice with Angular,Javascript ES6, and more.",
    width: "200",
    height: "34",
  },

  {
    id: 8,
    title: "Online Examination System",
    alt: "synap logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/synap.webp",
    desc: "    The online examination system, which is adopted by an increasing number of schools not only shows the validity and impartiality of examinations of some of their workload.",
    width: "200",
    height: "34",
  },
  {
    id: 9,
    title: "Sorting Visualizer",
    alt: "sortilizer logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/sortilizer.webp",
    desc: " This is the ideal project for you if you're looking for a fresh JavaScript project concept, want to learn JavaScript inside and out, or want to advance your JavaScript abilities.",
    width: "85",
    height: "21",
  },

  {
    id: 11,
    title: "Food Delivery App",
    alt: "swiggy logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/swiggy.webp",
    desc: " Build a food delivery app from scratch using your knowledge of the Spring framework, web services, and MySQL with a strong back-end to support operations. Learn to use latest frameworks",
    width: "200",
    height: "34",
  },
  {
    id: 12,
    title: "Social Media Applications",
    alt: "facebook logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/facebook.webp",
    desc: "  Immersing yourself in the field of socializing, hanging outwith friends and chilling. Build a full stack application like instagram and facebook.",
    width: "174",
    height: "47",
  },
];
